#!/bin/bash
# ==============================================================================
# VideoPopup - Quick Setup Script
# ==============================================================================
# This script helps you set up the complete VideoPopup stack
# Usage: chmod +x setup.sh && ./setup.sh
# ==============================================================================

set -e

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║           VideoPopup - Self-Hosted Setup Wizard              ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

# Check if using Coolify
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}Coolify Users: Quick Setup${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo "If you're using Coolify, we recommend:"
echo "1. Install Supabase via: Project > Resources > Add Supabase"
echo "2. Get API keys from Supabase resource's environment variables"
echo "3. Deploy frontend via: Project > New Resource > Git Repository"
echo "4. Use this script only for database migrations and edge functions"
echo ""
read -p "Are you using Coolify? (y/N): " USE_COOLIFY
if [ "$USE_COOLIFY" = "y" ] || [ "$USE_COOLIFY" = "Y" ]; then
    echo ""
    echo -e "${GREEN}✓ Using Coolify - You can skip Supabase installation steps${NC}"
    echo "Continue with this script for:"
    echo "  - Database migrations"
    echo "  - Edge functions setup (if not using Supabase edge functions)"
    echo ""
    read -p "Press Enter to continue..."
    echo ""
fi

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Check dependencies
check_dependency() {
    if command -v $1 &> /dev/null; then
        echo -e "${GREEN}✓${NC} $1 is installed"
        return 0
    else
        echo -e "${RED}✗${NC} $1 is not installed"
        return 1
    fi
}

echo -e "${BLUE}Checking dependencies...${NC}"
echo ""

check_dependency "docker" || { echo "Please install Docker first"; exit 1; }
check_dependency "docker-compose" || check_dependency "docker compose" || { echo "Please install Docker Compose first"; exit 1; }
check_dependency "node" || echo -e "${YELLOW}Node.js not found - needed for building frontend${NC}"
check_dependency "npm" || echo -e "${YELLOW}npm not found - needed for building frontend${NC}"

echo ""
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}Step 1: Environment Configuration${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""

if [ -f ".env" ]; then
    echo -e "${YELLOW}⚠ .env file already exists${NC}"
    read -p "Do you want to reconfigure? (y/N): " RECONFIG
    if [ "$RECONFIG" != "y" ] && [ "$RECONFIG" != "Y" ]; then
        echo "Keeping existing configuration..."
    else
        rm .env
    fi
fi

if [ ! -f ".env" ]; then
    echo "Let's configure your environment..."
    echo ""
    
    if [ "$USE_COOLIFY" = "y" ] || [ "$USE_COOLIFY" = "Y" ]; then
        echo -e "${YELLOW}Note: Get these values from your Supabase resource in Coolify${NC}"
        echo "  - Supabase URL: Resource > Details > URL"
        echo "  - Anon Key: Resource > Environment Variables > SUPABASE_ANON_KEY"
        echo "  - Service Role Key: Resource > Environment Variables > SUPABASE_SERVICE_ROLE_KEY"
        echo ""
    fi
    
    read -p "Enter your Supabase URL (e.g., https://supabase.yourdomain.com): " SUPABASE_URL
    read -p "Enter your Supabase Anon Key: " ANON_KEY
    read -p "Enter your Supabase Service Role Key: " SERVICE_KEY
    read -p "Enter your app domain (e.g., https://videopop.yourdomain.com): " APP_URL
    
    if [ "$USE_COOLIFY" != "y" ] && [ "$USE_COOLIFY" != "Y" ]; then
        read -p "Enter PostgreSQL password: " -s DB_PASSWORD
        echo ""
    else
        echo -e "${YELLOW}Note: Database password managed by Coolify${NC}"
        DB_PASSWORD="managed-by-coolify"
    fi
    
    cat > .env << EOF
# VideoPopup Environment Configuration
# Generated by setup.sh on $(date)

# Frontend (VITE)
VITE_SUPABASE_URL=$SUPABASE_URL
VITE_SUPABASE_PUBLISHABLE_KEY=$ANON_KEY
VITE_SUPABASE_PROJECT_ID=videopop

# Edge Functions
SUPABASE_URL=$SUPABASE_URL
SUPABASE_ANON_KEY=$ANON_KEY
SUPABASE_SERVICE_ROLE_KEY=$SERVICE_KEY
SUPABASE_DB_URL=postgresql://postgres:$DB_PASSWORD@\${SUPABASE_URL#https://}:5432/postgres

# App
SITE_URL=$APP_URL
EOF

    echo -e "${GREEN}✓ .env file created${NC}"
fi

echo ""
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}Step 2: Database Migration${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""

read -p "Do you want to run database migrations? (y/N): " RUN_MIGRATIONS
if [ "$RUN_MIGRATIONS" = "y" ] || [ "$RUN_MIGRATIONS" = "Y" ]; then
    source .env
    echo "Running migrations..."
    
    if command -v psql &> /dev/null; then
        psql "$SUPABASE_DB_URL" -f setup/complete-migration.sql
        echo -e "${GREEN}✓ Migrations completed${NC}"
    else
        echo -e "${YELLOW}psql not found. Please run migrations manually:${NC}"
        echo "psql \$SUPABASE_DB_URL -f setup/complete-migration.sql"
        echo ""
        echo "Or copy the contents of setup/complete-migration.sql"
        echo "to your Supabase SQL Editor"
    fi
fi

echo ""
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}Step 3: Build Frontend${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""

read -p "Do you want to build the frontend? (y/N): " BUILD_FRONTEND
if [ "$BUILD_FRONTEND" = "y" ] || [ "$BUILD_FRONTEND" = "Y" ]; then
    if command -v npm &> /dev/null; then
        echo "Installing dependencies..."
        npm install
        
        echo "Building for production..."
        npm run build
        
        echo -e "${GREEN}✓ Frontend built - output in 'dist/' folder${NC}"
    else
        echo -e "${RED}npm not found. Please install Node.js first${NC}"
    fi
fi

echo ""
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}Step 4: Edge Functions${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""

read -p "Do you want to start edge functions with Docker? (y/N): " START_EDGE
if [ "$START_EDGE" = "y" ] || [ "$START_EDGE" = "Y" ]; then
    echo "Starting edge functions..."
    docker compose -f setup/docker-compose.edge-functions.yaml up -d
    echo -e "${GREEN}✓ Edge functions started${NC}"
    echo ""
    echo "Edge function endpoints:"
    echo "  - http://localhost:8001 (get-widget)"
    echo "  - http://localhost:8002 (track-analytics)"
    echo "  - http://localhost:8003 (embed-script)"
    echo "  - http://localhost:8004 (send-lead-notification)"
    echo "  - http://localhost:8080 (nginx proxy - /functions/v1/*)"
fi

echo ""
echo -e "${GREEN}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}                    Setup Complete! 🎉                          ${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo "Next steps:"
echo "1. Deploy 'dist/' folder to your web server or Coolify"
echo "2. Create a user account via the signup form"
echo "3. Assign admin role in the database:"
echo "   INSERT INTO user_roles (user_id, role) VALUES ('your-uuid', 'admin');"
echo "4. Configure site settings in the admin dashboard"
echo ""
echo "Documentation: setup/DEPLOYMENT.md"
echo ""
